config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[new create show]
  resources :events, only: %i[index new create show] do
    resources :invitations, only: %i[new create]
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :date, presence: true
  validates :description, presence: true

  belongs_to :creator, class_name: 'User'
  has_many :invitations, foreign_key: :attended_event_id
  has_many :attendees, through: :invitations

  scope :past, -> { where('date < ?', Date.today) }
  scope :future, -> { where('date >= ?', Date.today) }

  # def self.future
  #   where('date > ?', Date.today)
  # end

  # def self.past
  #   where('date < ?', Date.today)
  # end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
  validates :attendee_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :invitations, foreign_key: :attendee_id
  has_many :attended_events, through: :invitations

  validates :name, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :email, presence: true, uniqueness: true, length: { minimum: 3 }

  scope :past, -> { where('date < ?', Date.today) }
  scope :future, -> { where('date >= ?', Date.today) }

  # def upcoming_events
  #   Event.where('date > ?', Date.today)
  # end
  # def previous_events
  #   Event.where('date < ?', Date.today)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:current_user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to '/login' unless logged_in?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authorized, only: %i[index show]
  def index
    @current_user = current_user
    @events = Event.all
    @past = Event.all.past
    @future = Event.all.future
  end

  def new
    @current_user = current_user
    @event = @current_user.created_events.build
  end

  def show
    @current_user = current_user
    @event = Event.find_by_id(params[:id])
    @invitation = Invitation.new
  end

  def create
    @current_user = current_user
    @event = @current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event
    else
      flash.now[:alert] = @event.errors.full_messages
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :date, :description)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def new
    @invitation = Invitation.new
  end

  def create
    @invitation = Invitation.new(invite_params)
    @invitation.attended_event_id = params[:event_id]
    event = Event.find_by(id: params[:event_id])
    user = User.find_by(id: params[:invitation][:attendee_id])

    event_attendees = event.attendees

    if user.nil?
      flash[:notice] = 'User Does Not Exist'
    elsif !event_attendees.include?(user)
      @invitation.save
    else
      flash[:notice] = 'User Already Invited'
    end
    redirect_to event_path(@invitation.attended_event_id)
  end

  private

  def invite_params
    params.require(:invitation).permit(:attendee_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: %i[new create]

  def destroy
    session[:current_user_id] = nil
    redirect_to '/login'
  end

  def new; end

  def create
    @user = User.find_by(email: params[:email])
    if @user
      session[:current_user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash.now[:notice] = 'User does not Exist'
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: %i[new create]

  def new
    @user = User.new
    @current_user = current_user
  end

  def create
    @user = User.new(signup_params)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to @user
    else
      flash.now[:alert] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @current_user = current_user
    @past = @current_user.created_events.past
    @future = @current_user.created_events.future
  end

  private

  def signup_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>All Events</h1>

<h2>Past Events</h2>
  <ul> 
  <% @past.each do |event|%>
  <li>
  <%= link_to event.name, event_path(event) %>
  </li>
  
<%end%>
</ul>

<h2>Future Events</h2>
<ul> 
  <% @future.each do |event|%>
  <li>
  <%= link_to event.name, event_path(event) %>

  </li>
<%end%>
</ul>

app/views/events/new.html.erb
<h1>Create New Event</h1>

  <%= form_for @event do |f|%>
    <%=f.label "Name" %>
    <%=f.text_field(:name)%>
    <%=f.label "Description" %>
    <%=f.text_field(:description)%>
    <%=f.label "Date" %>
    <%=f.date_field (:date) %> 
  
  <%=f.submit%>
<%end%>

app/views/events/show.html.erb
<h1>These are all attendees for "<i><%= @event.name %></i>" event </h1>
<ul>
<% @event.attendees.each do |attendee| %>
    <li> 
  <%= attendee.name %>
  </li>
<%end%>
</ul>

<% if current_user == @event.creator %>

<%= form_for [@event,@invitation] do |f|%>
  <%=f.label "Please Enter User ID" %>
  <%=f.text_field(:attendee_id)%>
  <%=f.submit 'Invite'%>
<%end%>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
    <% flash.each do |type, msg| %>
    <% if type == 'notice' %>
      <h5>  <%=  msg  %> </h5>
    <% else %>
      <ul>
        <% msg.each do |m| %>
          <li> <%= m %> </li>
        <% end %>
      </ul>
    <% end %>
    <% end %>
    <br>

      <% if @current_user != nil %>
        <span> Current user: </span>
        <%= @current_user.name %> <br>
        <%= link_to  "--- Logout ---   ", '/logout' %>
        <%= link_to  "--- Create new event   ---  ", new_event_path %>
        <%= link_to  "--- See all User events ---   ", user_path(@current_user) %>
        <% else %>
        <%= link_to  "--- Sign in ---   ", '/login' %>
      <% end %>

      <%= link_to  "--- Events List ---", events_path %>


    </nav>


    <%= yield %>
  </body>
</html>

app/views/users/_signup_form.html.erb
<%= form_for @user do |f|%>
  <%=f.label "Name" %>
  <%=f.text_field(:name)%>
  <%=f.label "Email" %>
  <%=f.email_field(:email)%>
  <%=f.submit%>
<%end%>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h2>Sign Up </h2>
<%= render 'signup_form'%>

app/views/users/show.html.erb
<h1>Showing all events created by user</h1>

  <h2>Previous Created Events</h2>
  <ul> 
  <% @past.each do |event|%>
  <li>
  <%= link_to event.name, event_path(event) %>
  </li>
  
<%end%>
</ul>
<h2>Upcoming Created Events</h2>
<ul> 
  <% @future.each do |event|%>
  <li>
  <%= link_to event.name, event_path(event) %>

  </li>
<%end%>
</ul>